In [1]:
age=20

In [2]:
type(age)

int

In [3]:
sales = 150.40

In [4]:
type(sales)

float

In [5]:
name = 'John'

In [12]:
a = '123'

In [13]:
type(a)

str

In [9]:
a=sales>50

In [20]:
type(a)

str

In [36]:
#List 
#Tuple 
#Dictionaries 
#Sets
l = [20,32,34,23,44,32]
t = (20,32,34,23,44,32)


In [29]:
l[1]=25

In [32]:
l.append(10)

In [34]:
l.clear()

In [38]:
l1=l.copy()

In [42]:
l.count(32)

2

In [44]:
l.append([10,20,30,40])

In [50]:
l

[20, 32, 34, 23, 44, 32, 10, 20, 30, 40, 50, 60]

In [49]:
l.extend([10,20,30,40,50,60])

In [53]:
l.index(10)

6

In [58]:
l.insert(6,0,5,6,5)

TypeError: insert() takes exactly 2 arguments (5 given)

In [60]:
len(l)

14

In [65]:
del l[-8]

In [74]:
l

[32, 34, 23, 44, 32, 0, 10, 20, 30]

In [73]:
l.pop(0)

20

In [75]:
l.remove(32)

In [77]:
l.reverse()

In [79]:
l.sort()

In [81]:
l.reverse()

In [84]:
t.count(32)

2

In [86]:
t

(20, 32, 34, 23, 44, 32)

In [85]:
t.index(32)

1

In [ ]:
for condition {
    statement1
}
statement2

In [ ]:
for condition:
    statement1
statement2

In [93]:
for i in l:
    print(i)
print('hi')

44
34
32
30
23
20
10
0
hi


In [101]:
for i in list(range(5,10)):
    print(i)

5
6
7
8
9


In [102]:
sales = [21343,45454,32434,32234]
profit = [4535,3243,4433,2322]

In [103]:
profit/sales

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [106]:
profitratio = []
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio

[0.21248184416436303,
 0.07134685616227394,
 0.13667756058457176,
 0.07203573866104114]

In [107]:
import numpy as np

In [108]:
sales

[21343, 45454, 32434, 32234]

In [109]:
profit

[4535, 3243, 4433, 2322]

In [111]:
sales_array = np.array(sales)

In [113]:
profit_array= np.array(profit)

In [117]:
sales_array

array([21343, 45454, 32434, 32234])

In [115]:
profit_array

array([4535, 3243, 4433, 2322])

In [118]:
profit_array/sales_array

array([0.21248184, 0.07134686, 0.13667756, 0.07203574])