In [1]:
#Dictonary  - Key Value pair 
myfirstdict = {'customer name': 'Rahul', 'Gender':'Male', 'Age':34, 'Region':'India'}

In [2]:
myfirstdict['Gender']

'Male'

In [3]:
myfirstdict['Sales']=250

In [4]:
myfirstdict

{'customer name': 'Rahul',
 'Gender': 'Male',
 'Age': 34,
 'Region': 'India',
 'Sales': 250}

In [5]:
len(myfirstdict)

5

In [7]:
customer_details = {'cid':[1,2,3,4,5],
                   'cname':['A','B','C','D','E'],
                   'Subject':['Python','Tableau','R','AWS','Python']}

In [8]:
customer_details

{'cid': [1, 2, 3, 4, 5],
 'cname': ['A', 'B', 'C', 'D', 'E'],
 'Subject': ['Python', 'Tableau', 'R', 'AWS', 'Python']}

In [9]:
customer_details['Subject']

['Python', 'Tableau', 'R', 'AWS', 'Python']

In [10]:
sales_details = {'c_id':[1,2,3,4,6],
                'Sales':[230,320,200,150,200]}

In [12]:
sales_details

{'c_id': [1, 2, 3, 4, 6], 'Sales': [230, 320, 200, 150, 200]}

In [13]:
import pandas as pd

In [16]:
customer_details = pd.DataFrame(customer_details)

In [17]:
sales_details = pd.DataFrame(sales_details)

In [20]:
type(customer_details)

pandas.core.frame.DataFrame

In [21]:
type(sales_details)

pandas.core.frame.DataFrame

In [22]:
customer_details

cid cname  Subject
0    1     A   Python
1    2     B  Tableau
2    3     C        R
3    4     D      AWS
4    5     E   Python

In [23]:
sales_details

c_id  Sales
0     1    230
1     2    320
2     3    200
3     4    150
4     6    200

In [24]:
pd.merge(customer_details,sales_details, left_on='cid',right_on='c_id')

cid cname  Subject  c_id  Sales
0    1     A   Python     1    230
1    2     B  Tableau     2    320
2    3     C        R     3    200
3    4     D      AWS     4    150

In [28]:
pd.merge(customer_details,sales_details, left_on='cid',right_on='c_id', how='outer')

cid cname  Subject  c_id  Sales
0  1.0     A   Python   1.0  230.0
1  2.0     B  Tableau   2.0  320.0
2  3.0     C        R   3.0  200.0
3  4.0     D      AWS   4.0  150.0
4  5.0     E   Python   NaN    NaN
5  NaN   NaN      NaN   6.0  200.0

In [30]:
dict([[3,2],[1,4],[4,5]])

{3: 2, 1: 4, 4: 5}

In [33]:
dict(((3,2),(1,4),(4,5)))

{3: 2, 1: 4, 4: 5}

In [34]:
#sets 
myfirstset = {1,2,2,3,3,3,3,3,3,4,5,6,6,6,6,6,6,6,6,7}

In [35]:
myfirstset

{1, 2, 3, 4, 5, 6, 7}

In [36]:
myfirstset[5]

TypeError: 'set' object is not subscriptable

In [40]:
myfirstset.add([30,40,50])

TypeError: unhashable type: 'list'

In [41]:
myfirstset.update([40,50,60])

In [45]:
myfirstset.remove(30)

KeyError: 30

In [58]:
myfirstset.discard(40)

In [59]:
myfirstset

{1, 2, 3, 4, 5, 6, 7, 50, 60}

In [64]:
myfirstset.pop()

2

In [65]:
myfirstset

{3, 4, 5, 6, 7, 50, 60}

In [70]:
myset1 = {70,80}

In [72]:
myfirstset

{3, 4, 5, 6, 7, 50, 60}

In [68]:
myfirstset.intersection(myset1)

{50, 60}

In [71]:
myfirstset.isdisjoint(myset1)

True

In [76]:
myset1 = {1,2,3,4,5}
myset2 = {1,2}
myset2.issubset(myset1)

True

In [78]:
customers = ['James','John','Mathew','Anderson']
order_id = [1,2,3,4]

for (c,o) in zip(customers, order_id):
    print('Hello',c, 'Your order id is', o)

Hello James Your order id is 1
Hello John Your order id is 2
Hello Mathew Your order id is 3
Hello Anderson Your order id is 4


In [80]:
s = 'Simpliv'
for i in s:
    print(i)

S
i
m
p
l
i
v


In [ ]:
while conditon {
    statement1
    statement2
}
statement3


In [ ]:
while condition:
    statement1
    statement2
    statement3


In [81]:
coupouns = 5
utilized = 0
while utilized<=5:
    print('Total coupouns left are:' , coupouns-utilized)
    utilized = utilized+1
print('No coupouns left')

Total coupouns left are: 5
Total coupouns left are: 4
Total coupouns left are: 3
Total coupouns left are: 2
Total coupouns left are: 1
Total coupouns left are: 0
No coupouns left


In [82]:
while False:
    print('Hi')
print('Hello')

Hello


In [88]:
marks = 92
if marks<40:
    print('You failed the exam')
elif marks >= 40 and marks <=70:
    print('You got 1st distinction')
elif marks >70 and marks <=90:
    print('You got very good marks')
else:
    print('You topped the exam')

You topped the exam


In [89]:
import numpy as np

In [90]:
sales = [3245,4545,3444,4543]
profit = [545,345,345,342]

In [92]:
profitatio = []
for i in range(0,len(sales)):
    profitatio.append(profit[i]/sales[i])
profitatio

[0.1679506933744222,
 0.07590759075907591,
 0.10017421602787456,
 0.075280651551838]

In [94]:
sales_array=np.array(sales)

In [95]:
profit_array = np.array(profit)

In [96]:
sales_array

array([3245, 4545, 3444, 4543])

In [97]:
profit_array

array([545, 345, 345, 342])

In [98]:
profit_array/sales_array

array([0.16795069, 0.07590759, 0.10017422, 0.07528065])

In [101]:
sales_array*2

array([6490, 9090, 6888, 9086])

In [102]:
sales*2

[3245, 4545, 3444, 4543, 3245, 4545, 3444, 4543]

In [105]:
sales1 = sales.copy()

In [106]:
sales_array_1 = sales_array.copy()

In [109]:
sales[0]=0

In [110]:
sales

[0, 4545, 3444, 4543]

In [111]:
sales1

[3245, 4545, 3444, 4543]

In [114]:
sales_array[0]=0

In [115]:
sales_array

array([   0, 4545, 3444, 4543])

In [116]:
sales_array_1

array([3245, 4545, 3444, 4543])

In [118]:
sales_2 = sales[0:2]

In [121]:
sales[1]=0

In [122]:
sales

[0, 0, 3444, 4543]

In [123]:
sales_2

[0, 4545]

In [126]:
sales_array_2 = sales_array[0:2]

In [129]:
sales_array[1]=0

In [134]:
sales_array

array([1000,    0, 3444, 4543])

In [132]:
sales_array_2[0]=1000

In [133]:
sales_array_2

array([1000,    0])

In [135]:
sales_us =[3245,3222,4452,4222]
sales_eu = [4354,3334,2344,3333]
sales_jp = [4354,3334,2234,3433]


In [143]:
profit_us = [543,456,554,334]
profit_eu = [456,434,422,323]
profit_jp = [432,222,323,222]

In [139]:
sales_matrix=np.array([sales_us, sales_eu, sales_jp])

In [144]:
profit_matrix = np.array([profit_us,profit_eu, profit_jp])

In [145]:
profit_matrix

array([[543, 456, 554, 334],
       [456, 434, 422, 323],
       [432, 222, 323, 222]])

In [146]:
sales_matrix

array([[3245, 3222, 4452, 4222],
       [4354, 3334, 2344, 3333],
       [4354, 3334, 2234, 3433]])

In [147]:
profit_matrix/sales_matrix

array([[0.16733436, 0.141527  , 0.12443845, 0.07910943],
       [0.10473128, 0.13017397, 0.18003413, 0.09690969],
       [0.09921911, 0.06658668, 0.14458371, 0.06466647]])

In [150]:
sales_matrix[1,2]

2344

In [151]:
sales_matrix

array([[3245, 3222, 4452, 4222],
       [4354, 3334, 2344, 3333],
       [4354, 3334, 2234, 3433]])

In [152]:
rdict = {'US':0, 'EU':1, 'JP':2}
qdict = {'Q1':0, 'Q2':1, 'Q3':2, 'Q4':3}

In [153]:
sales_matrix[rdict['EU']][qdict['Q3']]

2344

In [155]:
pd.read_csv('D:\\D\\Simpliv - ML\\tips.csv')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [158]:
import os
os.getcwd()
#os.chdir(r'D:\D\Simpliv - ML')

'D:\\D\\Simpliv - ML'

In [160]:
tips = pd.read_csv('tips.csv')

In [162]:
type(tips)

pandas.core.frame.DataFrame

In [163]:
len(tips)

244

In [164]:
len(tips.columns)

7

In [165]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [168]:
tips.head(1)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2

In [170]:
tips.tail(3)

total_bill   tip     sex smoker   day    time  size
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [172]:
tips[['total_bill','smoker','time','size']]

total_bill smoker    time  size
0         16.99     No  Dinner     2
1         10.34     No  Dinner     3
2         21.01     No  Dinner     3
3         23.68     No  Dinner     2
4         24.59     No  Dinner     4
..          ...    ...     ...   ...
239       29.03     No  Dinner     3
240       27.18    Yes  Dinner     2
241       22.67    Yes  Dinner     2
242       17.82     No  Dinner     2
243       18.78     No  Dinner     2

[244 rows x 4 columns]

In [173]:
tips[tips['time']=='Dinner']

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]

In [178]:
len(tips[(tips['time']=='Dinner') & (tips['tip']>5)])

15

In [177]:
tips[(tips['time']=='Dinner') | (tips['tip']>5)]

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[179 rows x 7 columns]

In [179]:
tips.groupby('sex').size()

sex
Female     87
Male      157
dtype: int64

In [180]:
tips.groupby(['smoker','sex']).size()

smoker  sex   
No      Female    54
        Male      97
Yes     Female    33
        Male      60
dtype: int64

In [181]:
tips.groupby(['smoker','sex']).agg({'tip':np.mean})

tip
smoker sex             
No     Female  2.773519
       Male    3.113402
Yes    Female  2.931515
       Male    3.051167